# Generated by Django 4.2.16 on 2024-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
